mysql> LOAD DATA LOCAL INFILE 'database/users.csv' INTO TABLE users FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

mysql> LOAD DATA LOCAL INFILE 'database/sessions.csv' INTO TABLE sessions FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';

mysql> LOAD DATA LOCAL INFILE 'database/payments.csv' INTO TABLE payments FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';


