CREATE TABLE items (
item_id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
price INT UNSIGNED NOT NULL DEFAULT 0
);

CREATE TABLE statuses (
status_id SERIAL PRIMARY KEY,
name VARCHAR(30) NOT NULL,
discount SMALLINT UNSIGNED DEFAULT 0
);

CREATE TABLE clients (
client_id SERIAL PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
second_name VARCHAR(30) NOT NULL,
vk_id VARCHAR(30) NOT NULL,
registration_dttm TIMESTAMP NOT NULL ,
status INT UNSIGNED NOT NULL REFERENCES  statuses(status_id) ON DELETE CASCADE 
);

CREATE TABLE visits (
vist_id SERIAL PRIMARY KEY,
dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
client INT UNSIGNED NOT NULL REFERENCES clients(client_id) ON DELETE CASCADE 
);

CREATE TABLE orders (
order_id SERIAL PRIMARY KEY,
client INT UNSIGNED NOT NULL REFERENCES clients(client_id) ON DELETE CASCADE,
total_price INT UNSIGNED DEFAULT 0,
dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE shifts (
shift_id SERIAL PRIMARY KEY,
start_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
end_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
role_id SERIAL PRIMARY KEY,
name VARCHAR(30) NOT NULL,
money_per_hour INT UNSIGNED DEFAULT 0
);

CREATE TABLE workers (
worker_id SERIAL PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
second_name VARCHAR(30) NOT NULL,
vk_id VARCHAR(30) NOT NULL,
first_day_dttm TIMESTAMP NOT NULL,
role INT UNSIGNED REFERENCES roles(role_id) ON DELETE CASCADE
);

CREATE TABLE providers (
provider_id SERIAL PRIMARY KEY,
name VARCHAR(30) NOT NULL,
email VARCHAR(40) NOT NULL,
phone_number VARCHAR(25) DEFAULT NULL
);

CREATE TABLE ingredients (
ingredient_id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
price INT UNSIGNED  NOT NULL DEFAULT 0 REFERENCES ingredients(ingredient_id) ON DELETE CASCADE,
provider INT UNSIGNED NOT NULL REFERENCES providers(provider_id) ON DELETE CASCADE
);

CREATE TABLE order_item_link (
order_item_link_id SERIAL PRIMARY KEY,
order_id INT UNSIGNED REFERENCES orders(order_id) ON DELETE CASCADE,
item INT UNSIGNED NOT NULL REFERENCES items(item_id) ON DELETE CASCADE
);

CREATE TABLE ingredient_item_link (
ingredient_item_link_id SERIAL PRIMARY KEY,
ingredient INT UNSIGNED NOT NULL REFERENCES ingredients(ingredient_id) ON DELETE CASCADE,
item INT UNSIGNED NOT NULL REFERENCES items(item_id) ON DELETE CASCADE,
quantity SMALLINT UNSIGNED NOT NULL
);


CREATE TABLE worker_shift_link (
worker_shift_link_id SERIAL PRIMARY KEY,
worker INT UNSIGNED NOT NULL REFERENCES workers(worker_id) ON DELETE CASCADE,
shift INT UNSIGNED NOT NULL REFERENCES shifts(shift_id) ON DELETE CASCADE
);